// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFII7MiXylghvG-t3k9Yj9ephIGtmLGTQ',
    appId: '1:881333074318:web:1f72532c5c7484c32cccdf',
    messagingSenderId: '881333074318',
    projectId: 'voguevoyage27',
    authDomain: 'voguevoyage27.firebaseapp.com',
    storageBucket: 'voguevoyage27.appspot.com',
    measurementId: 'G-NC742F4VL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANDfm7GoD4winvi5_PKV2sRiXf4t3cCKc',
    appId: '1:881333074318:android:107b4e1dba77b12a2cccdf',
    messagingSenderId: '881333074318',
    projectId: 'voguevoyage27',
    storageBucket: 'voguevoyage27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOgCCG0bBftlXfrkYssR8J_yHfrdOg-w',
    appId: '1:881333074318:ios:d4eb493381b6eba72cccdf',
    messagingSenderId: '881333074318',
    projectId: 'voguevoyage27',
    storageBucket: 'voguevoyage27.appspot.com',
    iosClientId: '881333074318-qejtu1srntc4m1lf6qsjnccndi252863.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOgCCG0bBftlXfrkYssR8J_yHfrdOg-w',
    appId: '1:881333074318:ios:623524a5ccf900992cccdf',
    messagingSenderId: '881333074318',
    projectId: 'voguevoyage27',
    storageBucket: 'voguevoyage27.appspot.com',
    iosClientId: '881333074318-pfqqn10uq5pvusa7g1tuseo80i8m8p20.apps.googleusercontent.com',
    iosBundleId: 'com.example.clothing.RunnerTests',
  );
}
