name: clothing
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.2.7
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:  
  assets:
    - assets/images/
  fonts:
    - family: Satify
      fonts: 
        - asset: assets/Satisfy/Satisfy-Regular.ttf


  uses-material-design: true
